### ISSUE TITLE
to many conflicts

### ISSUE THREAD

**Issue by Goddard** [shlomnissan/formbuilder#7]
This has a lot of conflicts with other css files.

How can I avoid this issue?

**Comment by shlomnissan** [comment]
Hi Goddard, the project is due to be updated. In the meantime, you will have to fix the css conflicts manually. Sorry :/

**Comment by Goddard** [comment]
no worries, thanks for the update.  Guess I will use a simpler library for the time being.

**Comment by dancuer92** [comment]
Hello!!
I'm Daniel Cuervo, I'm working on your form-builder. its a excelent job.

Need your help about how insert a dinamic table throught a input fields. for example: I want 4 rows and 3 column and the table shows that. 

My project try about a systematization of the formats (documents). and there are documents that contains tables and I need "draw them".

A table contains labels and inputs, and i need render it same the format.

I'm grateful if you can help me!!
